// This file was auto-generated by Fern from our API Definition.

package client

import (
	analytics "github.com/fern-demo/vapi-go-sdk/analytics"
	assistants "github.com/fern-demo/vapi-go-sdk/assistants"
	blocks "github.com/fern-demo/vapi-go-sdk/blocks"
	calls "github.com/fern-demo/vapi-go-sdk/calls"
	core "github.com/fern-demo/vapi-go-sdk/core"
	files "github.com/fern-demo/vapi-go-sdk/files"
	logs "github.com/fern-demo/vapi-go-sdk/logs"
	option "github.com/fern-demo/vapi-go-sdk/option"
	phonenumbers "github.com/fern-demo/vapi-go-sdk/phonenumbers"
	squads "github.com/fern-demo/vapi-go-sdk/squads"
	tools "github.com/fern-demo/vapi-go-sdk/tools"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Calls        *calls.Client
	Assistants   *assistants.Client
	PhoneNumbers *phonenumbers.Client
	Squads       *squads.Client
	Blocks       *blocks.Client
	Tools        *tools.Client
	Files        *files.Client
	Analytics    *analytics.Client
	Logs         *logs.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:       options.ToHeader(),
		Calls:        calls.NewClient(opts...),
		Assistants:   assistants.NewClient(opts...),
		PhoneNumbers: phonenumbers.NewClient(opts...),
		Squads:       squads.NewClient(opts...),
		Blocks:       blocks.NewClient(opts...),
		Tools:        tools.NewClient(opts...),
		Files:        files.NewClient(opts...),
		Analytics:    analytics.NewClient(opts...),
		Logs:         logs.NewClient(opts...),
	}
}
